project:
  title: "Data for Development: Asia"
  render:
    - "country/*/*.qmd"
# 6. Format Settings
#bibliography: shared/d4dasia-bib.json
#csl: shared/chicago-shortened-notes-bibliography-subsequent-author.csl
#reference-section-title: References
citeproc: false

format:
  lirneasia-typst:
    keep-typ: true 
    keep-md: true
